version: "3.3"  # optional since v1.27.0
services:
  server:
    build: .
    ports:
      - "8080:8080"

    entrypoint:
      - ./example-server
      - --secrets
      - server-secret
      - guide1-secret
      - guide2-secret

  guide1:
    build: .
    ports:
      - "8081:8080"

    entrypoint:
      - ./guide-server
      - --guideid
      - "1"
      - --secret
      - guide1-secret

  guide2:
    build: .
    ports:
      - "8082:8080"

    entrypoint:
      - ./guide-server
      - --guideid
      - "2"
      - --secret
      - guide2-secret

  client:
    build: .
  